dist: bionic
language: go
os: linux
jobs:
  include:
    - go: "1.14.x"
    - go: "1.14.x"
      osx_image: "xcode11.6"
      os: osx
    - go: "1.13.x"
    - go: "1.12.x"
      env:
        # on 1.12 this is needed to enable module support when the project is
        # checked out underneath $GOPATH/src (which Travis does); see
        # https://github.com/golang/go/issues/31857.
        GO111MODULE=on
install:
  - go get -t ./...
script:
  - gofmt -w -s .
  - go generate ./...
  - git diff --exit-code
  - go vet -composites=false ./...
  - go test -v ./...
